---
- name: Create Hive Path
  shell: mkdir -p {{ hive_config_path }}  
- name: Copy Hive
  copy: src={{ download_path }}/apache-hive-{{hive_version}}-bin.tar.gz dest=/tmp owner={{ user }} mode=755
  
- name: Unzip Hive
  shell: "tar zxf /tmp/apache-hive-{{hive_version}}-bin.tar.gz -C {{ hive_path }}"

- name: Fix bug Gua lib
  shell: "rm -rf {{ hive_full_path }}/lib/guava-19.0.jar"
- name: Fix bug Gua lib
  shell: "cp {{ hadoop_full_path }}/share/hadoop/hdfs/lib/guava-27.0-jre.jar  {{ hive_full_path }}/lib/"