---
- name: Copy Hadoop core-site.xml
  template: src=core-site.xml dest={{ hadoop_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Hadoop hdfs-site.xml
  template: src=hdfs-site.xml dest={{ hadoop_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Hadoop mapred-site.xml
  template: src=mapred-site.xml dest={{ hadoop_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Hadoop yarn-site.xml
  template: src=yarn-site.xml dest={{ hadoop_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Hadoop workers
  template: src=workers dest={{ hadoop_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Hadoop Env Script
  template: src=hadoop_env.sh dest=/etc/profile.d/ mode=755

- name: Set Hadoop Env
  shell: source /etc/profile.d/hadoop_env.sh
- name: Copy file Hadoop run server-start_master.sh
  template: src=start_master.sh dest={{ hadoop_path }}/hadoop-{{hadoop_version}}/sbin mode=755 owner={{ user }} group = {{ group }}
- name: Copy file Hadoop run server-start_node.sh
  template: src=start_node.sh dest={{ hadoop_path }}/hadoop-{{hadoop_version}}/sbin mode=755 owner={{ user }} group = {{ group }}
- name: Copy file Hadoop run server-start_second_master.sh
  template: src=start_second_master.sh dest={{ hadoop_path }}/hadoop-{{hadoop_version}}/sbin mode=755 owner={{ user }} group = {{ group }}