---
- name: Copy Hadoop core-site.xml
  template: src=core-site.xml dest={{ hadoop_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Hadoop hdfs-site.xml
  template: src=hdfs-site.xml dest={{ hadoop_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Hadoop mapred-site.xml
  template: src=mapred-site.xml dest={{ hadoop_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Hadoop yarn-site.xml
  template: src=yarn-site.xml dest={{ hadoop_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Hadoop workers
  template: src=workers dest={{ hadoop_config_path }} mode=644 owner={{ user }} group = {{ group }}

- name: Copy Hadoop Env Script
  template: src=hadoop_env.sh dest=/etc/profile.d/ mode=755

- name: Fix yarn with spark
  copy: src={{ ansible_path }}/path/spark-network-yarn_2.12-3.1.2.7.2.12.0-291.jar dest={{ hadoop_path }}/hadoop-{{hadoop_version}}/share/hadoop/yarn/lib owner={{ user }} mode=755
- name: Set Hadoop Env
  shell: source /etc/profile.d/hadoop_env.sh
- name: Copy file Hadoop run server-start_node1.sh
  template: src=start_node1.sh dest={{ hadoop_path }}/hadoop-{{hadoop_version}}/sbin mode=755 owner={{ user }} group = {{ group }}
- name: Copy file Hadoop run server-start_node2.sh
  template: src=start_node2.sh dest={{ hadoop_path }}/hadoop-{{hadoop_version}}/sbin mode=755 owner={{ user }} group = {{ group }}
- name: Copy file Hadoop run server-start_node3.sh
  template: src=start_node3.sh dest={{ hadoop_path }}/hadoop-{{hadoop_version}}/sbin mode=755 owner={{ user }} group = {{ group }}