---
- name: Copy kafka server.properties
  template: src=server.properties dest={{ kafka_fullpath }}/config mode=644 owner={{ user }} group = {{ group }}
- name: Change owner folder Kafka
  shell: sudo chown -R {{ user }}:{{ user }} {{ kafka_path }}