---
- name: Create Kafka path
  shell: mkdir -p {{ kafka_path }}
- name: Copy Kafka
  copy: src={{ download_path }}/kafka_{{kafka_version}}.tgz dest=/tmp owner={{ user }} mode=755
  
- name: Unzip Kafka
  shell: "tar zxf /tmp/kafka_{{kafka_version}}.tgz -C {{ kafka_path }}"

- name: Create Kafka Log
  shell: mkdir -p {{ kafka_log_dir }}